### ISSUE TITLE
[docs] Improvement in "QA testing "

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#41]
### What is the URL of the page?

general/development/process/qatesting.md

### What is the issue with this page?

We should change references from contact Helen to contact the QA team and turn them into a link with instructions on how to contact Helen (i.e. create a new issue?).

Pinging @wildgirl to know the best way to proceed here.

### Are you able to provide a patch for this?

Yes - I will create one

**Comment by wildgirl** [comment]
Hi Sara,

Thanks for highlighting the references to contacting me in https://docs.moodle.org/dev/QA_testing 

I've just removed them because HQ devs are automatically added to the test writers group and I can't think of anyone outside HQ ever asking to be be added to the group. It's part of the wider question though of how community members should contact HQ if they want to volunteer to help.

**Comment by sarjona** [comment]
Hi @wildgirl!
Thanks for checking this. I've prepared a pull-request to remove these references to the new page that we have created in docusaurus too :-)
